version: '3.8'

services:
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: scanner_postgres
  #   environment:
  #     POSTGRES_USER: scanner
  #     POSTGRES_PASSWORD: scanner_dev_password
  #     POSTGRES_DB: scanner
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U scanner"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    ports:
      - "3310:3310"
    volumes:
      - /tmp/scan_dir:/tmp/scan_dir
      - /home/rappjaco/s3Loader/clam_av/clamd.conf:/etc/clamav/clamd.conf
    restart: unless-stopped

volumes:
  postgres_data:
